<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\PresenceController;

/*
|--------------------------------------------------------------------------
| Api Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

Route::name('api.')
    ->prefix('api')
    ->group(function () {
        Route::post('/login', [AuthController::class, 'login'])->name(
            'api.login'
        );

        Route::middleware('auth:sanctum')->group(function () {
            Route::get('/presences', [
                PresenceController::class,
                'index',
            ])->name('presences.index');

            Route::post('/presences', [
                PresenceController::class,
                'store',
            ])->name('presences.store');

            Route::get('/presences/{presence}', [
                PresenceController::class,
                'show',
            ])->name('presences.show');

            Route::put('/presences/{presence}', [
                PresenceController::class,
                'update',
            ])->name('presences.update');

            Route::delete('/presences/{presence}', [
                PresenceController::class,
                'destroy',
            ])->name('presences.destroy');
        });
    });
